[project]
name = "auto-gen-examples"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "autogen>=0.7.2",
    "chess>=1.11.1",
    "ipykernel>=6.29.5",
    "python-dotenv>=1.0.1",
]
